version: '3'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    restart: always

  webserver:
    image: apache/airflow:2.9.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:mysecretpassword@host.docker.internal:5432/cafe_sales
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../scripts:/opt/airflow/sql_etl/scripts
      - ../sql_etl:/opt/airflow/sql_etl/sql_etl
      - ../raw data:/opt/airflow/sql_etl/raw_data

    command: webserver
    restart: always

  scheduler:
    image: apache/airflow:2.9.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:mysecretpassword@host.docker.internal:5432/cafe_sales
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ../scripts:/opt/airflow/sql_etl/scripts
      - ../sql_etl:/opt/airflow/sql_etl/sql_etl
      - ../raw data:/opt/airflow/sql_etl/raw_data

    command: scheduler
    restart: always

volumes:
  postgres-db-volume:
